#!/bin/bash                                                                                                                               

#this uses the qsub to submit jobs                                                                                                        

#if [ $# != 2 ];then
#    echo "arg1 - allocType, arg2 - bestClass"
#    exit 1
#fi
#alctyp=$1
#bstcl=$2

#bsub='/home/alnu/bin/tqsub -q hplong'                                                                                                    
errd="errfls3"
log="logfls3"
#jbend="do."$alctyp

#resfil="epsilonLibSvm/accBsdAna/200/results_1_3_0.mat"
#dtfil="epsilonLibSvm/accBsdAna/200/test/test_labels"

declare -a density=(10 15 20 25 30)
declare -a spreading=(15 25 30 35 45)
declare -a maxpeak=(1 3 5 7)


#declare -a stno=(3)                                                                                                                      
#declare -a strtyp=(1 2 3 4 5 6 8 11)                                                                                                     

qsz=hp
#algtyp=-100
#insmp=-100
#stpsmsz=-100
#mulwt=-100
#sstr=-100

for stn in "${density[@]}"
do
    #echo $stsz                                                                                                                           
    for sttyp in "${spreading[@]}"
    do
        for max in "${maxpeak[@]}"
        do

        #echo $styp                                                                                                                       
        evJbnm=$stn"."$sttyp"."$max
        errPt=$errd/"err."$evJbnm
        outPt=$errd/"out."$evJbnm
        logfl=$log/"log."$evJbnm
        #jbid=`$bsub -N $evJbnm -e $errPt -o $outPt ./runExFn.sh $dtfile $resfile $bestcl $stsz $styp $alctype $algtyp $inismp $stsmpsz $sstrp $multwt  $logfl`                                                                                                                     
        #echo "./runExFnV2.sh dtfile=$dtfil resfile=$resfil bestcl=$bstcl stsz=$stn styp=$sttyp alctype=$alctyp algtype=$algtyp inismp=$insmp stsmpsz=$stpsmsz sstrp=$sstr multwt=$mulwt logf=$logfl" | qsub -N $evJbnm -e $errPt -o $outPt 
                                       
        qsub -q $qsz -N $evJbnm -e $errPt -o $outPt -v stsz=$stn,styp=$sttyp,maxp=$max,logf=$logfl submit_script.sh
        echo "$evJbnm submitted"
        
        done

    done

done






