#!/bin/bash                                                                     

#PBS -l nodes=1:ppn=4                                                           
cd $PBS_O_WORKDIR

#---above two lines are important----------read about qsub to understand, in short nodes specify number of nodes requested, ppn is number of cores, PBD_O_WORKDIR cd's
#to current working directory..otw qsub by default starts in home directory


echo $@                                                                        


#echo $logf                                                                     
#runExptFn is the matlab code and the rest are the arguments it takes

/opt/matlab/8.6/bin/matlab  -nodisplay -r "New_Dataset $ $ $;exit" > $logf
